# Generated by Django 5.2.7 on 2025-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
